import { FC } from "react";
import { Box, Flex, ProviderCard, Text } from "../components";
import React from "react";
import { useNavigate } from "react-router-dom";

const Providers: FC = () => {
    const navigate = useNavigate();
    const onClick = (provider: any) => {
        navigate('/provider/' + provider.id);
    };

    return (
        <Box>
            <Text as="h2" mb={20}>Providers</Text>
            <Flex flexWrap="wrap" gap={50}>
                {PROVIDERS.map((provider) => <ProviderCard onClick={() => onClick(provider)} width="200px" key={provider.id} name={provider.name} logoUrl={provider.logoUrl} />)}
            </Flex>
        </Box>
    );
};

export default Providers;

const PROVIDERS = [
    {
        "id": "2230",
        "code": "bankinter_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": "bankinter",
        "group_name": "Bankinter S.A.",
        "hub": null,
        "name": "Bankinter Web Banking",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/es/bankinter_es.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": true,
        "customer_notified_on_sign_in": false,
        "created_at": "2014-11-13T13:17:57Z",
        "updated_at": "2024-06-11T10:39:06Z"
    },
    {
        "id": "2249",
        "code": "carrefour_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": "carrefour",
        "group_name": "Carrefour",
        "hub": null,
        "name": "Carrefour Web Banking",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/es/carrefour_es.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": true,
        "customer_notified_on_sign_in": false,
        "created_at": "2014-11-24T12:36:04Z",
        "updated_at": "2024-10-11T07:15:04Z"
    },
    {
        "id": "2280",
        "code": "iberiacards_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": null,
        "group_name": null,
        "hub": null,
        "name": "Iberia Cards Personal Web Banking",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/es/iberiacards_es.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": false,
        "customer_notified_on_sign_in": false,
        "created_at": "2014-12-19T17:28:14Z",
        "updated_at": "2024-06-11T10:39:06Z"
    },
    {
        "id": "2292",
        "code": "la_caixa_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": "caixa",
        "group_name": "CaixaBank",
        "hub": null,
        "name": "Caixabank Web Banking",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/es/la_caixa_es.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": true,
        "customer_notified_on_sign_in": false,
        "created_at": "2015-01-15T14:51:14Z",
        "updated_at": "2024-06-11T10:39:06Z"
    },
    {
        "id": "2465",
        "code": "evobanco_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": "bankinter",
        "group_name": "Bankinter S.A.",
        "hub": null,
        "name": "EVO Banco Web Banking",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/es/evobanco_es.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": true,
        "customer_notified_on_sign_in": false,
        "created_at": "2015-11-16T16:44:28Z",
        "updated_at": "2024-06-11T10:39:06Z"
    },
    {
        "id": "2550",
        "code": "popular_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": "santander",
        "group_name": "Santander",
        "hub": "santander_es",
        "name": "Banco Popular Web Banking",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/es/popular_es.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": true,
        "customer_notified_on_sign_in": false,
        "created_at": "2015-12-10T09:42:48Z",
        "updated_at": "2024-06-11T10:39:06Z"
    },
    {
        "id": "2612",
        "code": "arquia_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": null,
        "group_name": null,
        "hub": null,
        "name": "Arquia Web Banking",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/es/arquia_es.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": true,
        "customer_notified_on_sign_in": false,
        "created_at": "2015-12-14T12:23:24Z",
        "updated_at": "2024-06-11T10:39:06Z"
    },
    {
        "id": "2613",
        "code": "santander_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": "santander",
        "group_name": "Santander",
        "hub": "santander_es",
        "name": "Santander Web Banking",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/es/santander_es.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": true,
        "customer_notified_on_sign_in": false,
        "created_at": "2015-12-15T17:26:36Z",
        "updated_at": "2024-06-11T10:39:06Z"
    },
    {
        "id": "2616",
        "code": "ibercaja_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": "ibercaja",
        "group_name": "Ibercaja Banco",
        "hub": null,
        "name": "Ibercaja Web Banking",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/es/ibercaja_es.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": true,
        "customer_notified_on_sign_in": false,
        "created_at": "2015-12-18T11:59:06Z",
        "updated_at": "2024-06-11T10:39:06Z"
    },
    {
        "id": "2621",
        "code": "santander_empresas_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": "santander",
        "group_name": "Santander",
        "hub": null,
        "name": "Santander Empresas Web Banking",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/es/santander_es.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": true,
        "customer_notified_on_sign_in": false,
        "created_at": "2015-12-23T14:51:59Z",
        "updated_at": "2024-06-11T10:39:06Z"
    },
    {
        "id": "2631",
        "code": "kutxabank_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": "bbva",
        "group_name": "Banco Bilbao Vizcaya Argentaria",
        "hub": null,
        "name": "Kutxabank Web Banking",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/es/kutxabank_es.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": true,
        "customer_notified_on_sign_in": false,
        "created_at": "2016-01-06T15:35:47Z",
        "updated_at": "2024-06-11T10:39:06Z"
    },
    {
        "id": "2659",
        "code": "american_express_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": "american_express",
        "group_name": "American Express",
        "hub": "american_express",
        "name": "American Express Web Banking",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/es/american_express_es.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": true,
        "customer_notified_on_sign_in": false,
        "created_at": "2016-02-25T10:38:52Z",
        "updated_at": "2024-06-11T10:39:06Z"
    },
    {
        "id": "2735",
        "code": "popular_e_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": "wizink",
        "group_name": "WiZink Bank S.A.",
        "hub": null,
        "name": "WiZink (Popular-e) Web Banking",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/es/popular_e_es.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": false,
        "customer_notified_on_sign_in": false,
        "created_at": "2016-06-06T10:06:49Z",
        "updated_at": "2024-10-21T14:26:57Z"
    },
    {
        "id": "8116",
        "code": "tarjeta_miles_and_more_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": "caixa",
        "group_name": "CaixaBank",
        "hub": null,
        "name": "Miles&More (Caixabank Payments & Consumer)",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/xf/placeholder_global.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": false,
        "customer_notified_on_sign_in": false,
        "created_at": "2024-02-29T14:46:58Z",
        "updated_at": "2024-06-11T10:39:07Z"
    },
    {
        "id": "8120",
        "code": "repsol_mas_visa_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": null,
        "group_name": null,
        "hub": null,
        "name": "Tarjeta Repsol Más Visa",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/xf/placeholder_global.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": false,
        "customer_notified_on_sign_in": false,
        "created_at": "2024-03-05T07:15:25Z",
        "updated_at": "2024-06-11T10:39:06Z"
    },
    {
        "id": "8152",
        "code": "edenred_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": null,
        "group_name": null,
        "hub": null,
        "name": "Tickets Restaurant Edenred",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/xf/placeholder_global.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": true,
        "customer_notified_on_sign_in": false,
        "created_at": "2024-03-08T07:15:23Z",
        "updated_at": "2024-06-21T07:15:05Z"
    },
    {
        "id": "8155",
        "code": "el_corte_ingles_es",
        "country_code": "ES",
        "bic_codes": [],
        "dynamic_registration_code": null,
        "identification_codes": [],
        "group_code": null,
        "group_name": null,
        "hub": null,
        "name": "El Corte Inglés financiera tarjeta",
        "status": "active",
        "mode": "web",
        "regulated": false,
        "logoUrl": "https://d1uuj3mi6rzwpm.cloudfront.net/logos/providers/xf/placeholder_global.svg",
        "timezone": "Europe/Madrid",
        "supported_iframe_embedding": true,
        "optional_interactivity": false,
        "customer_notified_on_sign_in": false,
        "created_at": "2024-03-23T07:15:18Z",
        "updated_at": "2024-06-11T10:39:06Z"
    }
]